version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/drone-tui
    binary: drone-tui
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/arch-err/drone-tui/internal/version.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
